### ISSUE TITLE
wav2raw and SPTK

### ISSUE THREAD

**Issue by ddavout** [Zguy/wav2raw#1]
How do you compare wav2raw and x2x from SPTK (http://sourceforge.net/projects/sp-tk)
(if it is better...) Can we use wav2raw along with SPTK ?
Thanks

**Comment by Zguy** [comment]
I'm not sure I understand the question. I don't know what SPTK is, but from a cursory glance I wouldn't say that this little utility is comparable to it. All wav2raw does is extract the audio data from wav files and puts it in a raw file (without any headers). You could easily achieve the same thing with Audacity.
